## 0. Setting up

In [1]:
import numpy as np
import pandas as pd

In [2]:
def normalize(a):
    return a / np.linalg.norm(a)

In [3]:
normalize(np.array([1, -1, np.sqrt(2)]))

array([ 0.5       , -0.5       ,  0.70710678])

## 1. Geometric modelling

In [4]:
# Input A, B coordinates
A = np.array([0, 0])
B = np.array([7, 7])

# Input vector d
d = np.array([2, 2])

# Input unit
unit = 10

print("The middle point of A and B is: ", (A + B) / 2)
print("The point that takes (units) * d distance from A is: ", A + unit * normalize(d))

The middle point of A and B is:  [3.5 3.5]
The point that takes (units) * d distance from A is:  [7.07106781 7.07106781]


In [5]:
# Input A, B coordinates
A = np.array([0, 0])
B = np.array([7, 7])

# Input unit & delta
unit = 10
delta = 0.2

d = normalize(B - A)
print("Vector d: ", d)
for i in range(unit):
    print(f"T{i} = {A + i*d}")
    print(f"T{i}_{1} = {A + i*d + delta*np.array([d[1], -d[0]])}")
    print(f"T{i}_{2} = {A + i*d - delta*np.array([d[1], -d[0]])}")

Vector d:  [0.70710678 0.70710678]
T0 = [0. 0.]
T0_1 = [ 0.14142136 -0.14142136]
T0_2 = [-0.14142136  0.14142136]
T1 = [0.70710678 0.70710678]
T1_1 = [0.84852814 0.56568542]
T1_2 = [0.56568542 0.84852814]
T2 = [1.41421356 1.41421356]
T2_1 = [1.55563492 1.27279221]
T2_2 = [1.27279221 1.55563492]
T3 = [2.12132034 2.12132034]
T3_1 = [2.2627417  1.97989899]
T3_2 = [1.97989899 2.2627417 ]
T4 = [2.82842712 2.82842712]
T4_1 = [2.96984848 2.68700577]
T4_2 = [2.68700577 2.96984848]
T5 = [3.53553391 3.53553391]
T5_1 = [3.67695526 3.39411255]
T5_2 = [3.39411255 3.67695526]
T6 = [4.24264069 4.24264069]
T6_1 = [4.38406204 4.10121933]
T6_2 = [4.10121933 4.38406204]
T7 = [4.94974747 4.94974747]
T7_1 = [5.09116882 4.80832611]
T7_2 = [4.80832611 5.09116882]
T8 = [5.65685425 5.65685425]
T8_1 = [5.79827561 5.51543289]
T8_2 = [5.51543289 5.79827561]
T9 = [6.36396103 6.36396103]
T9_1 = [6.50538239 6.22253967]
T9_2 = [6.22253967 6.50538239]


In [6]:
def perp(vector):
    perp_vector = np.array([vector[1], -vector[0], 0])
    assert np.dot(vector, perp_vector) == 0
    return perp_vector

def circumscribed_center(A, B, C, rotation=[0, 1, 2]):
    print("Part 1: Find the circumscribed center of ABC")
    a = B - A
    b = C - B
    c = A - C
    S = A + (a / 2) + (1/2) * (np.dot(c, b) / np.dot(c, perp(a))) * perp(a)
    
    print("Recheck: ")
    SA = np.linalg.norm(A - S)
    SB = np.linalg.norm(B - S)
    SC = np.linalg.norm(C - S)
    print("SA: ", np.linalg.norm(A - S))
    print("SB: ", np.linalg.norm(B - S))
    print("SC: ", np.linalg.norm(C - S))
    assert SA == SB == SC
    
    print("It passed the test, so S", S, " is the center of circumscribed circle\n")
    
    print("Part 2: Find the vector passed S and perp to ABC, in order\n", pd.Series(["A", "B", "C"])[rotation].to_numpy())
    vect = None
    AB = B - A
    AC = C - A
    BA = A - B
    BC = C - B
    CA = A - C
    CB = B - C
    if rotation[0] == 0: # ABC or ACB
        vect = np.cross(AB, AC)
    if rotation[0] == 1: # BAC or BCA
        vect = np.cross(BA, BC)
    if rotation[0] == 2:
        vect = np.cross(CA, CB)
    print("Result vector (before normalized): ", vect)
    print("Result vector (after normalized): ", normalize(vect))

In [7]:
# Input A, B and C
A = np.array([2, 3, 0])
B = np.array([2, 1, 0])
C = np.array([5, 1, 0])

circumscribed_center(A, B, C)

Part 1: Find the circumscribed center of ABC
Recheck: 
SA:  1.8027756377319946
SB:  1.8027756377319946
SC:  1.8027756377319946
It passed the test, so S [3.5 2.  0. ]  is the center of circumscribed circle

Part 2: Find the vector passed S and perp to ABC, in order
 ['A' 'B' 'C']
Result vector (before normalized):  [0 0 6]
Result vector (after normalized):  [0. 0. 1.]


## 2. Graphic pipeline

In [8]:
def translate(x, y, z=None):
    if z is None:
        return np.array([
            [1, 0, x],
            [0, 1, y],
            [0, 0, 1]
        ])
    else:
        return np.array([
            [1, 0, 0, x],
            [0, 1, 0, y],
            [0, 0, 1, z],
            [0, 0, 0, 1]
        ])        

In [9]:
def rotate(theta, x=None, y=None, z=None):
    t = theta * np.pi / 180.0
    if x is None or y is None or z is None:
        return np.array([
            [np.cos(t), -np.sin(t), 0],
            [np.sin(t),  np.cos(t), 0],
            [0, 0, 1]
        ])
    elif x == 1 and y == 0 and z == 0:
        return np.array([
            [1, 0, 0, 0],
            [0, np.cos(t), -np.sin(t), 0],
            [0, np.sin(t),  np.cos(t), 0],
            [0, 0, 0, 1]
        ])
    elif x == 0 and y == 1 and z == 0:
        return np.array([
            [np.cos(t), 0, np.sin(t), 0],
            [0, 1, 0, 0],
            [-np.sin(t), 0, np.cos(t), 0],
            [0, 0, 0, 1]
        ])
    elif x == 0 and y == 0 and z == 1:
        return np.array([
            [np.cos(t), -np.sin(t), 0, 0],
            [np.sin(t),  np.cos(t), 0, 0],
            [0, 0, 1, 0],
            [0, 0, 0, 1]
        ])
    else:
        raise ValueError(f'Have you input the correct format of x, y, z? Received {(x, y, z)}')

In [10]:
def scale(x, y, z=None):
    if z is None:
        return np.array([
            [x, 0, 0],
            [0, y, 0],
            [0, 0, 1]
        ])
    else:
        return np.array([
            [x, 0, 0, 0],
            [0, y, 0, 0],
            [0, 0, z, 0],
            [0, 0, 0, 1]
        ])

In [46]:
def lookAt(eye_x, eye_y, eye_z, look_x, look_y, look_z, up_x, up_y, up_z):
    print("------LOOK AT-------")
    eye = np.array([eye_x, eye_y, eye_z])
    look = np.array([look_x, look_y, look_z])
    up = np.array([up_x, up_y, up_z])
    
    n = eye - look
    print("Vector n: ", n)
    n = normalize(n)
    print("Vector n: ", n)
    u = np.cross(up, n)
    print("Vector u: ", u)
    u = normalize(u)
    print("Vector u: ", u)
    v = np.cross(n, u)
    print("Vector v: ", v)
    v = normalize(v)
    print("Vector v: ", v)
    
    print("Before normalization")
    
    print("Vector u: ", u)
    print("Vector v: ", v)
    
    n = normalize(n)
    u = normalize(u)
    v = normalize(v)
    
    print("After normalization")
    print("Vector n: ", n)
    print("Vector u: ", u)
    print("Vector v: ", v)
    
    d = np.array([
        np.dot(-eye, u),
        np.dot(-eye, v),
        np.dot(-eye, n)
    ])
    
    print("\nVector d: ", d)
    
    return np.array([
        [u[0], u[1], u[2], d[0]],
        [v[0], v[1], v[2], d[1]],
        [n[0], n[1], n[2], d[2]],
        [0, 0, 0, 1]
    ])

In [12]:
def ortho(left, right, bottom, top, near, far):
    return np.array([
        [2/(right - left), 0, 0, -(right + left)/(right - left)],
        [0, 2/(top - bottom), 0, -(top + bottom)/(top - bottom)],
        [0, 0, 2/(near - far), -(far + near)/(far - near)],
        [0, 0, 0, 1]
    ])

In [13]:
def frustum(left, right, bottom, top, near, far):
    return np.array([
        [2*near/(right - left), 0, (right + left)/(right - left), 0],
        [0, 2*near/(top - bottom), (top + bottom)/(top - bottom), 0],
        [0, 0, -(far + near)/(far - near), -2*far*near/(far - near)],
        [0, 0, -1, 0]
    ])

In [14]:
def identity(dimension=3):
    if dimension == 3:
        return np.array([
            [1, 0, 0, 0],
            [0, 1, 0, 0],
            [0, 0, 1, 0],
            [0, 0, 0, 1]
        ])
    elif dimension == 2:
        return np.array([
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1]
        ])

In [15]:
def matrix_mul(dimension=3, *matrix):
    result = identity(dimension)
    matrix = list(matrix)
    matrix.reverse()
    for m in matrix:
        result = m @ result
        print("Multiply with:\n", m, "\nto get\n", result)
    return result

In [16]:
def transform_point(point, matrix):
    print(matrix)
    return matrix @ point

def transform_vector(vector, matrix):
    print("Transformed matrix: \n", np.linalg.inv(matrix).T)
    return np.linalg.inv(matrix).T @ point

In [17]:
m = matrix_mul(3, scale(2,2,2))
print(m)

Multiply with:
 [[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 1]] 
to get
 [[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 1]]
[[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 1]]


In [18]:
point = np.array([2, 3, 4, 1])
transform_point(point, m)

[[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 1]]


array([4, 6, 8, 1])

In [19]:
point = np.array([1, 2, 3, 1])
transform_point(point, m)

[[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 1]]


array([2, 4, 6, 1])

In [20]:
vector = np.array([1, 1, 1])
vector = normalize(vector)
print("Vector after normalized: ", vector)
vector = transform_vector(vector, m)
print("Result vector: ", vector[:3])
print("After re-normalized: ", normalize(vector[:3]))

Vector after normalized:  [0.57735027 0.57735027 0.57735027]
Transformed matrix: 
 [[0.5 0.  0.  0. ]
 [0.  0.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]
Result vector:  [0.5 1.  1.5]
After re-normalized:  [0.26726124 0.53452248 0.80178373]


In [21]:
lookAt(-5, 0, 5, 0, 0, 0, 0, 1, 0)

------LOOK AT-------
Before normalization
Vector n:  [-5  0  5]
Vector u:  [5 0 5]
Vector v:  [ 0 50  0]
After normalization
Vector n:  [-0.70710678  0.          0.70710678]
Vector u:  [0.70710678 0.         0.70710678]
Vector v:  [0. 1. 0.]

Vector d:  [ 0.          0.         -7.07106781]


array([[ 0.70710678,  0.        ,  0.70710678,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.70710678,  0.        ,  0.70710678, -7.07106781],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [22]:
ortho(2, 3, 4, 5, 6, 7)

array([[  2.,   0.,   0.,  -5.],
       [  0.,   2.,   0.,  -9.],
       [  0.,   0.,  -2., -13.],
       [  0.,   0.,   0.,   1.]])

In [23]:
frustum(2, 3, 4, 5, 6, 7)

array([[ 12.,   0.,   5.,   0.],
       [  0.,  12.,   9.,   0.],
       [  0.,   0., -13., -84.],
       [  0.,   0.,  -1.,   0.]])

In [24]:
matrix_mul(3, translate(2, 3, 4), translate(-1, -1, -1))

Multiply with:
 [[ 1  0  0 -1]
 [ 0  1  0 -1]
 [ 0  0  1 -1]
 [ 0  0  0  1]] 
to get
 [[ 1  0  0 -1]
 [ 0  1  0 -1]
 [ 0  0  1 -1]
 [ 0  0  0  1]]
Multiply with:
 [[1 0 0 2]
 [0 1 0 3]
 [0 0 1 4]
 [0 0 0 1]] 
to get
 [[1 0 0 1]
 [0 1 0 2]
 [0 0 1 3]
 [0 0 0 1]]


array([[1, 0, 0, 1],
       [0, 1, 0, 2],
       [0, 0, 1, 3],
       [0, 0, 0, 1]])

In [25]:
matrix_mul(3, scale(0.5, 0.5, 1.0), rotate(45, 0, 0, 1), translate(2, 3, 4))

Multiply with:
 [[1 0 0 2]
 [0 1 0 3]
 [0 0 1 4]
 [0 0 0 1]] 
to get
 [[1 0 0 2]
 [0 1 0 3]
 [0 0 1 4]
 [0 0 0 1]]
Multiply with:
 [[ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]] 
to get
 [[ 0.70710678 -0.70710678  0.         -0.70710678]
 [ 0.70710678  0.70710678  0.          3.53553391]
 [ 0.          0.          1.          4.        ]
 [ 0.          0.          0.          1.        ]]
Multiply with:
 [[0.5 0.  0.  0. ]
 [0.  0.5 0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]] 
to get
 [[ 0.35355339 -0.35355339  0.         -0.35355339]
 [ 0.35355339  0.35355339  0.          1.76776695]
 [ 0.          0.          1.          4.        ]
 [ 0.          0.          0.          1.        ]]


array([[ 0.35355339, -0.35355339,  0.        , -0.35355339],
       [ 0.35355339,  0.35355339,  0.        ,  1.76776695],
       [ 0.        ,  0.        ,  1.        ,  4.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

## 3. Interpolation

### 3.1. Gouraud shading

In [26]:
def gouraud_shading(A, B, C, P, C_A, C_B, C_C):
    AB = B - A
    AC = C - A
    PA = A - P
    PB = B - P
    PC = C - P
    
    S_ABC = np.linalg.norm(np.cross(AB, AC)) / 2
    S_PAB = np.linalg.norm(np.cross(PA, PB)) / 2
    S_PBC = np.linalg.norm(np.cross(PB, PC)) / 2
    S_PCA = np.linalg.norm(np.cross(PC, PA)) / 2
    
    alpha_a = S_PBC / S_ABC
    alpha_b = S_PCA / S_ABC
    alpha_c = S_PAB / S_ABC
    
    assert np.isclose(S_PAB + S_PBC + S_PCA, S_ABC)
    assert np.isclose(alpha_a + alpha_b + alpha_c, 1)
    
    C_P = alpha_a * C_A + alpha_b * C_B + alpha_c * C_C
    
    print("S_ABC: ", S_ABC)
    print("S_PAB: ", S_PAB)
    print("S_PBC: ", S_PBC)
    print("S_PCA: ", S_PCA)
    print("alphas: ", alpha_a, alpha_b, alpha_c)
    print("C_P: ", C_P)
    return C_P

In [27]:
# Input A, B, C, P
A = np.array([0, 3, 1])
B = np.array([3, 0, 1])
C = np.array([3, 3, 1])
P = np.array([2.5, 2.6, 1])

# Input C_A, C_B, C_C
# Notes: red: [1,0,0], green: [0,1,0], blue: [0,0,1]
C_A = np.array([1, 0, 0])
C_B = np.array([0, 1, 0])
C_C = np.array([0, 0, 1])

gouraud_shading(A, B, C, P, C_A, C_B, C_C)

S_ABC:  4.5
S_PAB:  3.15
S_PBC:  0.75
S_PCA:  0.5999999999999999
alphas:  0.16666666666666666 0.1333333333333333 0.7
C_P:  [0.16666667 0.13333333 0.7       ]


array([0.16666667, 0.13333333, 0.7       ])

### 3.2. Phong's shading

In [28]:
def interpol(A, B, C, P, n_A, n_B, n_C):
    AB = B - A
    AC = C - A
    BA = A - B
    BC = C - B
    CA = A - C
    CB = B - C
    PA = A - P
    PB = B - P
    PC = C - P
    
#     n_A = np.cross(AB, AC)
#     n_B = np.cross(BA, BC)
#     n_C = np.cross(CA, CB)
    
    S_ABC = np.linalg.norm(np.cross(AB, AC)) / 2
    S_PAB = np.linalg.norm(np.cross(PA, PB)) / 2
    S_PBC = np.linalg.norm(np.cross(PB, PC)) / 2
    S_PCA = np.linalg.norm(np.cross(PC, PA)) / 2
    
    alpha_a = S_PBC / S_ABC
    alpha_b = S_PCA / S_ABC
    alpha_c = S_PAB / S_ABC
    
    assert np.isclose(S_PAB + S_PBC + S_PCA, S_ABC)
    assert np.isclose(alpha_a + alpha_b + alpha_c, 1)
    
    n_P = alpha_a * n_A + alpha_b * n_B + alpha_c * n_C
    
    print("n_A: ", n_A)
    print("n_B: ", n_B)
    print("n_C: ", n_C)
    print("S_ABC: ", S_ABC)
    print("S_PAB: ", S_PAB)
    print("S_PBC: ", S_PBC)
    print("S_PCA: ", S_PCA)
    print("alphas: ", alpha_a, alpha_b, alpha_c)
    print("n_P: ", n_P)
    return n_P

In [29]:
def phong_shading(l, n, v, K, I, alpha):
    
    # Normalize all vectors
    l = normalize(l)
    n = normalize(n)
    v = normalize(v)
    
    # Reflecting vector
    r = normalize(2 * np.dot(l, n) * n - l)
    
    print("Vector l:", l)
    print("Vector n:", n)
    print("Vector v:", v)
    print("Vector r (before normalized): ", 2 * np.dot(l, n) * n - l)
    print("Vector r (after normalized): ", r)
    
    g = np.array([
        np.max(np.dot(l, n), 0),
        np.power(np.max(np.dot(r, v), 0), alpha),
        1
    ])
    print("Vector g: ", g)
    print("K dot I:\n", np.multiply(K, I))
    I = np.multiply(K, I) @ g
    return I

In [30]:
# Input l (to_light vector). l = light_position - P
l = np.array([1, 2, 4])

# Input n (normal vector to the surface)
# Way 1: Input directly
# n = np.array([3, -2, 3])

# Way 2: Get through 3 points ABC and point P inside
A = np.array([1, 0, 2])
B = np.array([1, 5, 2])
C = np.array([5, 10, 2])
P = np.array([1, 1, 2])
n_A = np.array([2, 4, 5])
n_B = np.array([2, 3, 4])
n_C = np.array([2, 1, 3])

# Input v (to_viewer vector). v = -P
v = np.array([-1, -2, -1])

# Input alpha (shininess coefficient)
alpha = 3

K = np.array([
    [0.4, 0.5, 0.4],
    [0.2, 0.6, 0.6],
    [0.7, 0.8, 0.9]
])

I = np.array([
    [0.5, 0.5, 0.5],
    [0.6, 0.6, 0.6],
    [1, 1, 1]
])

n = interpol(A, B, C, P, n_A, n_B, n_C)
phong_shading(l, n, v, K, I, alpha)

n_A:  [2 4 5]
n_B:  [2 3 4]
n_C:  [2 1 3]
S_ABC:  10.0
S_PAB:  0.0
S_PBC:  8.0
S_PCA:  2.0
alphas:  0.8 0.2 0.0
n_P:  [2.  3.8 4.8]
Vector l: [0.21821789 0.43643578 0.87287156]
Vector n: [0.31053505 0.59001659 0.74528411]
Vector v: [-0.40824829 -0.81649658 -0.40824829]
Vector r (before normalized):  [0.38782601 0.71504763 0.5816338 ]
Vector r (after normalized):  [0.38782601 0.71504763 0.5816338 ]
Vector g:  [ 0.97580596 -0.94008102  1.        ]
K dot I:
 [[0.2  0.25 0.2 ]
 [0.12 0.36 0.36]
 [0.7  0.8  0.9 ]]


array([0.16014094, 0.13866755, 0.83099935])

In [31]:
A = np.array([-3, 0, -1])
B = np.array([1, 3, 4])
C = np.array([3, 3, -3])

In [35]:
n_ABC = normalize(np.cross(B-A, C-A))
n_ABC

array([-0.47913248,  0.86700163, -0.13689499])

In [38]:
D = A + 5 * n_ABC
D

array([-5.3956624 ,  4.33500815, -1.68447497])

In [39]:
np.linalg.norm(D - A)

5.0

In [41]:
P = A + 10 * (-n_ABC)
P

array([ 1.7913248 , -8.6700163 ,  0.36894994])

In [48]:
eye = P
look = B
up = np.array([0,1,0])
print(eye, look, up)
m_view = lookAt(eye[0], eye[1], eye[2], look[0], look[1], look[2], 0, 1, 0)
m_view

[ 1.7913248  -8.6700163   0.36894994] [1 3 4] [0 1 0]
------LOOK AT-------
Vector n:  [  0.7913248  -11.6700163   -3.63105006]
Vector n:  [ 0.0646114  -0.95285284 -0.296474  ]
Vector u:  [-0.296474   0.        -0.0646114]
Vector u:  [-0.97706641  0.         -0.21293479]
Vector v:  [ 0.20289552  0.3034328  -0.93100051]
Vector v:  [ 0.20289552  0.3034328  -0.93100051]
Before normalization
Vector u:  [-0.97706641  0.         -0.21293479]
Vector v:  [ 0.20289552  0.3034328  -0.93100051]
After normalization
Vector n:  [ 0.0646114  -0.95285284 -0.296474  ]
Vector u:  [-0.97706641  0.         -0.21293479]
Vector v:  [ 0.20289552  0.3034328  -0.93100051]

Vector d:  [ 1.82880558  2.61080811 -8.26760561]


array([[-0.97706641,  0.        , -0.21293479,  1.82880558],
       [ 0.20289552,  0.3034328 , -0.93100051,  2.61080811],
       [ 0.0646114 , -0.95285284, -0.296474  , -8.26760561],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [58]:
A_C = m_view @ np.append(A, [1])
A_C

array([ 4.9729396 ,  2.93312206, -8.16496581,  1.        ])

In [59]:
B_C = m_view @ np.append(B, [1])
B_C

array([-1.11022302e-16,  2.22044605e-16, -1.22474487e+01,  1.00000000e+00])

In [60]:
B

array([1, 3, 4])

In [61]:
 -1.22474487e+01

-12.2474487

In [62]:
C_C = m_view @ np.append(C, [1])
C_C

array([ -0.46358929,   6.92279459, -10.04290795,   1.        ])

In [63]:
P = (B+C)/2
P

array([2. , 3. , 0.5])

In [64]:
Q = (A+P)/2
Q

array([-0.5 ,  1.5 , -0.25])

In [66]:
# Way 1
Q_C = m_view @ np.append(Q, [1])
Q_C

array([ 2.37057248,  3.19725968, -9.65507207,  1.        ])

In [68]:
P_C = (B_C + C_C) / 2
P_C, B_C, C_C

(array([ -0.23179465,   3.4613973 , -11.14517833,   1.        ]),
 array([-1.11022302e-16,  2.22044605e-16, -1.22474487e+01,  1.00000000e+00]),
 array([ -0.46358929,   6.92279459, -10.04290795,   1.        ]))

In [70]:
Q_C = (A_C + P_C) / 2
Q_C

array([ 2.37057248,  3.19725968, -9.65507207,  1.        ])

In [72]:
P_eye = A + 10 * (-n_ABC)
P_eye

array([ 1.7913248 , -8.6700163 ,  0.36894994])

In [74]:
P_lightsource = np.array([10, 10, 10])

In [101]:
l = P_lightsource - Q_C[:3]
Q_C, l

(array([ 2.37057248,  3.19725968, -9.65507207,  1.        ]),
 array([ 7.62942752,  6.80274032, 19.65507207]))

In [78]:
normalize(l)

array([0.36394719, 0.82777059, 0.42701088])

In [87]:
n_A = np.array([-0.585, -0.792, -0.174])
n_B = np.array([-0.333, -0.170, 0.927])
n_C = np.array([0.224, -0.165, -0.960])

M = np.array([[ -0.898, 0.000, 0.439, 0.000],
 [ -0.399, 0.419, -0.816, 0.000],
 [ -0.184, -0.908, -0.376, 0.000],
 [ -1.191, -9.821, -0.483, 1.000]]
)
M

array([[-0.898,  0.   ,  0.439,  0.   ],
       [-0.399,  0.419, -0.816,  0.   ],
       [-0.184, -0.908, -0.376,  0.   ],
       [-1.191, -9.821, -0.483,  1.   ]])

In [89]:
n_A = M @ np.append(n_A, [1])
n_B = M @ np.append(n_B, [1])
n_C = M @ np.append(n_C, [1])
n_A, n_B, n_C

(array([0.448944, 0.043551, 0.8922  , 9.559009]),
 array([ 0.705987, -0.694795, -0.13292 ,  2.618432]),
 array([-0.622592,  0.624849,  0.469564,  2.817361]))

In [91]:
n_A = n_A / n_A[3]
n_B = n_B / n_B[3]
n_C = n_C / n_C[3]
n_A, n_B, n_C

(array([0.04696554, 0.00455602, 0.09333604, 1.        ]),
 array([ 0.26962205, -0.26534773, -0.0507632 ,  1.        ]),
 array([-0.22098411,  0.22178521,  0.16666803,  1.        ]))

In [93]:
n_A = normalize(n_A[:3])
n_B = normalize(n_B[:3])
n_C = normalize(n_C[:3])
n_A, n_B, n_C

(array([0.44906341, 0.04356258, 0.89243731]),
 array([ 0.70640197, -0.69520339, -0.13299813]),
 array([-0.62304468,  0.62530332,  0.46990541]))

In [98]:
n_P = interpol(A[:3], B[:3], C[:3], Q[:3], n_A, n_B, n_C)
n_P

n_A:  [0.44906341 0.04356258 0.89243731]
n_B:  [ 0.70640197 -0.69520339 -0.13299813]
n_C:  [-0.62304468  0.62530332  0.46990541]
S_ABC:  21.914607000811127
S_PAB:  5.478651750202781
S_PBC:  10.95730350040556
S_PCA:  5.4786517502027845
alphas:  0.49999999999999983 0.2500000000000001 0.24999999999999997
n_P:  [0.24537103 0.00430627 0.53044548]


array([0.24537103, 0.00430627, 0.53044548])

In [96]:
Q_C[:3]

array([ 2.37057248,  3.19725968, -9.65507207])

In [103]:
n_P = normalize(n_P)
n_P

array([0.41982249, 0.0073679 , 0.90757633])

In [ ]:
K = np.array([
    [0.6, 0.8, 0.8],
    [1,0, 0.8, 0.4],
    [0.6, 0.8, 0.2]
])

I = np.array([
    [1, 0.4, 1],
    [1, 0.4, 1],
    [1, 0.4, 1]
])

phong_shading()