# Homework on Transformation

In [13]:
import numpy as np
    
# Function to get transformation matrix in 2D
def translate2d(x, y):
    return np.array([
        [1, 0, x],
        [0, 1, y],
        [0, 0, 1]
    ])

def scale2d(x_scale, y_scale):
    return np.array([
        [x_scale, 0, 0],
        [0, y_scale, 0],
        [0, 0, 1]
    ])

def refect2d():
    return scaling(-1, -1)

def rotate2d(anrad):
    return np.array([
        [np.cos(anrad), -np.sin(anrad), 0],
        [np.sin(anrad), np.cos(anrad), 0],
        [0, 0, 1]
    ])

def rotate_in_degree2d(angle):
    #Change the angle to radian
    anrad = np.pi * angle / 180
    return rotate2d(anrad)

def shear2d(h=0, g=0):
    return np.array([
        [1, h, 0],
        [g, 1, 0],
        [0, 0, 1]
    ])

def homo2d(vector):
    return np.array([[vector[0,0]],[vector[1,0]],[1]])

def transformation2d(vector, *transformation):
    M = transformation[0]
    if len(transformation) > 1:
        for i in range(1, len(transformation)):
            M = M @ transformation[i]
    return M @ homo2d(vector)

In [14]:
vector = np.array([[0], [5]])
transformation2d(vector, translate2d(6,0), rotate_in_degree2d(45), scale2d(0.5, 0.5))

array([[4.23223305],
       [1.76776695],
       [1.        ]])

In [27]:
# Function to get transformation matrix in 3D
def translate3d(x, y, z):
    return np.array([
        [1, 0, 0, x],
        [0, 1, 0, y],
        [0, 0, 1, z],
        [0, 0, 0, 1]
    ])

def scale3d(x_scale, y_scale, z_scale):
    return np.array([
        [x_scale, 0, 0, 0],
        [0, y_scale, 0, 0],
        [0, 0, z_scale, 0],
        [0, 0, 0, 1]
    ])

def refect3d():
    return scaling(-1, -1, -1)

def rotate3d(angle, x, y, z):
    anrad = np.pi * angle / 180
    if z == 1.0 and x == 0.0 and y == 0.0:
        return np.array([
            [np.cos(anrad), -np.sin(anrad), 0, 0],
            [np.sin(anrad), np.cos(anrad), 0, 0],
            [0, 0, 1, 0],
            [0, 0, 0, 1]
        ])
    elif x == 1.0 and y == 0.0 and z == 0.0:
        return np.array([
            [1,0,0,0],
            [0,np.cos(anrad), -np.sin(anrad),0],
            [0,np.sin(anrad), np.cos(anrad),0],
            [0,0,0,1]
        ])
    elif x == 0.0 and y == 1.0 and z = 0.0:
        return np.array([
            [1,0,0,0],
            []
        ])

def shear3d(a=0, b=0, c=0, d=0, e=0, f=0):
    return np.array([
        [1, a, b, 0],
        [c, 1, d, 0],
        [e, f, 1, 0],
        [0, 0, 0, 1]
    ])

def identity3d():
    return np.array([
        [1,0,0,0],
        [0,1,0,0],
        [0,0,1,0],
        [0,0,0,1]
    ])

def homo3d(vector):
    return np.array([[vector[0,0]],[vector[1,0]],[vector[2,0]],[1]])

def transformation3d(vector, *transformation):
    M = transformation[0]
    if len(transformation) > 1:
        for i in range(1, len(transformation)):
            M = M @ transformation[i]
    return M @ homo3d(vector)

def printTransMatrix(*trans):
    M = trans[0]
    if len(trans) > 1:
        for i in range(1, len(trans)):
            M = M @ trans[i]
    return M

In [28]:
C = np.array([[0], [5], [0], [1]])

m1 = identity3d()
print(m1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [29]:
m2 = m1 @ translate3d(6.0, 0.0, 0.0)
print(m2)

[[1. 0. 0. 6.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
m3 = m2 @ rotate3d(45, 0.0, 0.0, 1.0)
print(m3)

[[ 0.70710678 -0.70710678  0.          6.        ]
 [ 0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [31]:
m4 = m3 @ scale3d(0.5, 0.5, 1.0)
print(m4)

[[ 0.35355339 -0.35355339  0.          6.        ]
 [ 0.35355339  0.35355339  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
